package com.amelendez.lgo.storage.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.amelendez.lgo.storage.dao.Languo;

import com.amelendez.lgo.storage.dao.LanguoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig languoDaoConfig;

    private final LanguoDao languoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        languoDaoConfig = daoConfigMap.get(LanguoDao.class).clone();
        languoDaoConfig.initIdentityScope(type);

        languoDao = new LanguoDao(languoDaoConfig, this);

        registerDao(Languo.class, languoDao);
    }
    
    public void clear() {
        languoDaoConfig.getIdentityScope().clear();
    }

    public LanguoDao getLanguoDao() {
        return languoDao;
    }

}
