package com.amelendez.lgo.storage.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LANGUO".
 */
public class Languo {

    private Long id;
    /** Not-null value. */
    private String term;
    /** Not-null value. */
    private String definition;
    private String example;
    private int hits;
    private float level;
    private java.util.Date insertDate;
    private java.util.Date changedDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Languo() {
    }

    public Languo(Long id) {
        this.id = id;
    }

    public Languo(Long id, String term, String definition, String example, int hits, float level, java.util.Date insertDate, java.util.Date changedDate) {
        this.id = id;
        this.term = term;
        this.definition = definition;
        this.example = example;
        this.hits = hits;
        this.level = level;
        this.insertDate = insertDate;
        this.changedDate = changedDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTerm() {
        return term;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTerm(String term) {
        this.term = term;
    }

    /** Not-null value. */
    public String getDefinition() {
        return definition;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public String getExample() {
        return example;
    }

    public void setExample(String example) {
        this.example = example;
    }

    public int getHits() {
        return hits;
    }

    public void setHits(int hits) {
        this.hits = hits;
    }

    public float getLevel() {
        return level;
    }

    public void setLevel(float level) {
        this.level = level;
    }

    public java.util.Date getInsertDate() {
        return insertDate;
    }

    public void setInsertDate(java.util.Date insertDate) {
        this.insertDate = insertDate;
    }

    public java.util.Date getChangedDate() {
        return changedDate;
    }

    public void setChangedDate(java.util.Date changedDate) {
        this.changedDate = changedDate;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
